version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-52-86-33-50.compute-1.amazonaws.com
            port: '5432'
            database: ddoihbvjj2lu1r
            ssl: true
            schema: schema.graphql
            user: qdrryxewsvdeah
            password: c7ad2dfddcac7f2739479a6061d47d3bec248b30f600866959cd216e9a4106f5
            migrations: true